import { AnalysisReport } from '@aiops/shared';
import { Injectable, Logger } from '@nestjs/common';

import { AnalysisAgentService } from '../../agents/analysis-agent.service';
import { LinearService } from '../../providers/linear.service';
import { ExecutionContext } from '../execution.service';

@Injectable()
export class AnalysisStep {
  private readonly logger = new Logger(AnalysisStep.name);

  constructor(
    private readonly analysisAgent: AnalysisAgentService,
    private readonly linearService: LinearService,
  ) {}

  async execute(context: ExecutionContext): Promise<{
    success: boolean;
    data?: AnalysisReport;
    error?: string;
    extra?: { ticketId?: string; ticketUrl?: string };
  }> {
    this.logger.log(`[Run ${context.runId}] Starting analysis step`);

    if (!context.logs || !context.repository || !context.schema) {
      this.logger.error(
        `[Run ${context.runId}] Missing required context - logs: ${!!context.logs}, repository: ${!!context.repository}, schema: ${!!context.schema}`,
      );
      return {
        success: false,
        error: 'Missing required context (logs, repository, or schema)',
      };
    }

    try {
      this.logger.log(
        `[Run ${context.runId}] Calling analysis agent with ${context.logs.length} logs`,
      );
      const analysis = await this.analysisAgent.analyze(
        context.logs,
        context.repository,
        context.schema,
      );
      this.logger.log(
        `[Run ${context.runId}] Analysis agent completed - Error: ${analysis.errorType}, Severity: ${analysis.severity}`,
      );

      // Create Linear ticket
      const integration = context.integrations.get('TICKETING');
      let ticketId: string | undefined;
      let ticketUrl: string | undefined;

      this.logger.log(
        `[Run ${context.runId}] TICKETING integration found: ${!!integration}`,
      );

      if (integration) {
        const config = integration.config as Record<string, string>;
        this.logger.log(
          `[Run ${context.runId}] Creating Linear ticket with teamId: ${config.teamId}, projectId: ${config.projectId || 'none'}`,
        );

        const ticketTitle = `[AIOps] ${analysis.errorType}: ${analysis.summary}`;
        const ticketDescription = `## Analysis Report

**Severity**: ${analysis.severity}
**Error Type**: ${analysis.errorType}
**Confidence**: ${(analysis.confidence * 100).toFixed(0)}%

### Summary
${analysis.summary}

### Root Cause
${analysis.rootCause}

### Affected Files
${analysis.affectedFiles.map((f) => `- \`${f}\``).join('\n')}

### Suggested Fix
${analysis.suggestedFix}

---
*Generated by AIOps Self-Healing Pipeline*`;

        this.logger.debug(`[Run ${context.runId}] Ticket title: ${ticketTitle}`);

        const ticket = await this.linearService.createIssue(
          config,
          ticketTitle,
          ticketDescription,
        );

        if (ticket) {
          ticketId = ticket.id;
          ticketUrl = ticket.url;
          this.logger.log(
            `[Run ${context.runId}] Linear ticket created successfully - ID: ${ticketId}, URL: ${ticketUrl}`,
          );
        } else {
          this.logger.warn(
            `[Run ${context.runId}] Linear ticket creation returned null - check Linear service logs`,
          );
        }
      } else {
        this.logger.warn(
          `[Run ${context.runId}] No TICKETING integration configured, skipping ticket creation`,
        );
      }

      return {
        success: true,
        data: analysis,
        extra: { ticketId, ticketUrl },
      };
    } catch (error) {
      this.logger.error(
        `[Run ${context.runId}] Analysis step failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
        error instanceof Error ? error.stack : undefined,
      );
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Analysis failed',
      };
    }
  }
}
