import { AnalysisReport } from '@aiops/shared';
import { Injectable } from '@nestjs/common';

import { AnalysisAgentService } from '../../agents/analysis-agent.service';
import { LinearService } from '../../providers/linear.service';
import { ExecutionContext } from '../execution.service';

@Injectable()
export class AnalysisStep {
  constructor(
    private readonly analysisAgent: AnalysisAgentService,
    private readonly linearService: LinearService,
  ) {}

  async execute(context: ExecutionContext): Promise<{
    success: boolean;
    data?: AnalysisReport;
    error?: string;
    extra?: { ticketId?: string; ticketUrl?: string };
  }> {
    if (!context.logs || !context.repository || !context.schema) {
      return {
        success: false,
        error: 'Missing required context (logs, repository, or schema)',
      };
    }

    try {
      const analysis = await this.analysisAgent.analyze(
        context.logs,
        context.repository,
        context.schema,
      );

      // Create Linear ticket
      const integration = context.integrations.get('TICKETING');
      let ticketId: string | undefined;
      let ticketUrl: string | undefined;

      if (integration) {
        const ticket = await this.linearService.createIssue(
          integration.config as Record<string, string>,
          `[AIOps] ${analysis.errorType}: ${analysis.summary}`,
          `## Analysis Report

**Severity**: ${analysis.severity}
**Error Type**: ${analysis.errorType}
**Confidence**: ${(analysis.confidence * 100).toFixed(0)}%

### Summary
${analysis.summary}

### Root Cause
${analysis.rootCause}

### Affected Files
${analysis.affectedFiles.map((f) => `- \`${f}\``).join('\n')}

### Suggested Fix
${analysis.suggestedFix}

---
*Generated by AIOps Self-Healing Pipeline*`,
        );

        if (ticket) {
          ticketId = ticket.id;
          ticketUrl = ticket.url;
        }
      }

      return {
        success: true,
        data: analysis,
        extra: { ticketId, ticketUrl },
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Analysis failed',
      };
    }
  }
}
