import { RemediationResult, REMEDIATION_CONFIDENCE_THRESHOLD } from '@aiops/shared';
import { Injectable } from '@nestjs/common';

import { RemediationAgentService } from '../../agents/remediation-agent.service';
import { GitHubService } from '../../providers/github.service';
import { ExecutionContext } from '../execution.service';

@Injectable()
export class RemediationStep {
  constructor(
    private readonly remediationAgent: RemediationAgentService,
    private readonly githubService: GitHubService,
  ) {}

  async execute(context: ExecutionContext): Promise<{
    success: boolean;
    data?: RemediationResult;
    error?: string;
  }> {
    if (!context.analysis || !context.repository) {
      return {
        success: false,
        error: 'Missing required context (analysis or repository)',
      };
    }

    try {
      const remediation = await this.remediationAgent.remediate(
        context.analysis,
        context.repository,
      );

      if (!remediation.applied) {
        return {
          success: true,
          data: remediation,
        };
      }

      // Create PR if confidence is high enough
      if (context.analysis.confidence >= REMEDIATION_CONFIDENCE_THRESHOLD) {
        const integration = context.integrations.get('REPOSITORY');
        if (integration && remediation.changes.length > 0) {
          const pr = await this.githubService.createPullRequest(
            integration.config as Record<string, string>,
            remediation.changes,
            `[AIOps] Fix: ${context.analysis.summary}`,
            `## Automated Fix

This PR was automatically generated by the AIOps Self-Healing Pipeline.

### Analysis
- **Error Type**: ${context.analysis.errorType}
- **Severity**: ${context.analysis.severity}
- **Confidence**: ${(context.analysis.confidence * 100).toFixed(0)}%

### Root Cause
${context.analysis.rootCause}

### Changes Made
${remediation.changes.map((c) => `- **${c.path}**: ${c.description}`).join('\n')}

${context.ticketUrl ? `### Related Ticket\n${context.ticketUrl}` : ''}

---
*Generated by AIOps Self-Healing Pipeline*`,
          );

          if (pr) {
            remediation.pullRequestUrl = pr.url;
          }
        }
      }

      return {
        success: true,
        data: remediation,
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Remediation failed',
      };
    }
  }
}
