import { RemediationResult, REMEDIATION_CONFIDENCE_THRESHOLD } from '@aiops/shared';
import { Injectable, Logger } from '@nestjs/common';

import { RemediationAgentService } from '../../agents/remediation-agent.service';
import { GitHubService } from '../../providers/github.service';
import { ExecutionContext } from '../execution.service';

@Injectable()
export class RemediationStep {
  private readonly logger = new Logger(RemediationStep.name);

  constructor(
    private readonly remediationAgent: RemediationAgentService,
    private readonly githubService: GitHubService,
  ) {}

  async execute(context: ExecutionContext): Promise<{
    success: boolean;
    data?: RemediationResult;
    error?: string;
  }> {
    this.logger.log(`[Run ${context.runId}] Starting remediation step`);

    if (!context.analysis || !context.repository) {
      this.logger.error(
        `[Run ${context.runId}] Missing required context - analysis: ${!!context.analysis}, repository: ${!!context.repository}`,
      );
      return {
        success: false,
        error: 'Missing required context (analysis or repository)',
      };
    }

    try {
      this.logger.log(`[Run ${context.runId}] Calling remediation agent`);
      const remediation = await this.remediationAgent.remediate(
        context.analysis,
        context.repository,
      );
      this.logger.log(
        `[Run ${context.runId}] Remediation agent completed - Applied: ${remediation.applied}, Changes: ${remediation.changes.length}`,
      );

      if (!remediation.applied) {
        this.logger.log(`[Run ${context.runId}] Remediation not applied, skipping PR creation`);
        return {
          success: true,
          data: remediation,
        };
      }

      // Create PR if confidence is high enough
      this.logger.log(
        `[Run ${context.runId}] Confidence: ${context.analysis.confidence}, Threshold: ${REMEDIATION_CONFIDENCE_THRESHOLD}`,
      );

      if (context.analysis.confidence >= REMEDIATION_CONFIDENCE_THRESHOLD) {
        const integration = context.integrations.get('REPOSITORY');
        this.logger.log(`[Run ${context.runId}] REPOSITORY integration found: ${!!integration}`);

        if (integration && remediation.changes.length > 0) {
          const config = integration.config as Record<string, string>;
          this.logger.log(
            `[Run ${context.runId}] Creating PR with ${remediation.changes.length} changes for repo: ${config.owner}/${config.repo}`,
          );

          const pr = await this.githubService.createPullRequest(
            config,
            remediation.changes,
            `[AIOps] Fix: ${context.analysis.summary}`,
            `## Automated Fix

This PR was automatically generated by the AIOps Self-Healing Pipeline.

### Analysis
- **Error Type**: ${context.analysis.errorType}
- **Severity**: ${context.analysis.severity}
- **Confidence**: ${(context.analysis.confidence * 100).toFixed(0)}%

### Root Cause
${context.analysis.rootCause}

### Changes Made
${remediation.changes.map((c) => `- **${c.path}**: ${c.description}`).join('\n')}

${context.ticketUrl ? `### Related Ticket\n${context.ticketUrl}` : ''}

---
*Generated by AIOps Self-Healing Pipeline*`,
          );

          if (pr) {
            remediation.pullRequestUrl = pr.url;
            this.logger.log(`[Run ${context.runId}] PR created successfully: ${pr.url}`);
          } else {
            this.logger.warn(`[Run ${context.runId}] PR creation returned null - check GitHub service logs`);
          }
        } else {
          this.logger.warn(
            `[Run ${context.runId}] Skipping PR creation - integration: ${!!integration}, changes: ${remediation.changes.length}`,
          );
        }
      } else {
        this.logger.log(
          `[Run ${context.runId}] Confidence below threshold, skipping PR creation`,
        );
      }

      return {
        success: true,
        data: remediation,
      };
    } catch (error) {
      this.logger.error(
        `[Run ${context.runId}] Remediation step failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
        error instanceof Error ? error.stack : undefined,
      );
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Remediation failed',
      };
    }
  }
}
